use Electro
go
--Thêm NSX
insert into NhaSanXuat (TenNSX, ThongTin) values ('Dell', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into NhaSanXuat (TenNSX, ThongTin) values ('HP', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.');
insert into NhaSanXuat (TenNSX, ThongTin) values ('Tempsoft', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.');
insert into NhaSanXuat (TenNSX, ThongTin) values ('Lenovo', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into NhaSanXuat (TenNSX, ThongTin) values ('Apple', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.');
insert into NhaSanXuat (TenNSX, ThongTin) values ('Sony', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into NhaSanXuat (TenNSX, ThongTin) values ('Microsoft', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.');
insert into NhaSanXuat (TenNSX, ThongTin) values ('SamSung', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into NhaSanXuat (TenNSX, ThongTin) values ('Toshiba', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into NhaSanXuat (TenNSX, ThongTin) values ('Razor', 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');

--Thêm NCC
insert into NhaCungCap (TenNCC, DiaChi, Email, DienThoai) values ('Flashset', '5 South Pass', 'kbourdel0@deviantart.com', '7479511413');
insert into NhaCungCap (TenNCC, DiaChi, Email, DienThoai) values ('Skyba', '26 Express Crossing', 'ughest1@csmonitor.com', '6296617418');
insert into NhaCungCap (TenNCC, DiaChi, Email, DienThoai) values ('Npath', '38377 Forest Alley', 'iseeley2@noaa.gov', '2118090594');
insert into NhaCungCap (TenNCC, DiaChi, Email, DienThoai) values ('Wikizz', '87 Orin Drive', 'tcobbald3@home.pl', '8073029790');
insert into NhaCungCap (TenNCC, DiaChi, Email, DienThoai) values ('Kwilith', '38112 Washington Lane', 'cyukhnin4@booking.com', '3134342007');
insert into NhaCungCap (TenNCC, DiaChi, Email, DienThoai) values ('Skipstorm', '119 Muir Court', 'idamper5@hp.com', '1946727573');
insert into NhaCungCap (TenNCC, DiaChi, Email, DienThoai) values ('Tavu', '102 Waxwing Center', 'vkhotler6@ameblo.jp', '9479542377');
insert into NhaCungCap (TenNCC, DiaChi, Email, DienThoai) values ('Topiclounge', '9889 Derek Place', 'agouth7@time.com', '4725813163');
insert into NhaCungCap (TenNCC, DiaChi, Email, DienThoai) values ('Yakidoo', '5 Amoth Parkway', 'pheister8@goo.ne.jp', '7933411350');
insert into NhaCungCap (TenNCC, DiaChi, Email, DienThoai) values ('Roombo', '4 Trailsway Junction', 'mmakeswell9@dot.gov', '6791381273');

